# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ lib/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ lib/api/2.0/mocks lib/api/redfish-1.0/mocks ]
      controllersDirs: [ lib/api/2.0, lib/api/redfish-1.0 ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    _swagger_renderer:
      name: swagger_render
      templateNameKey: x-view

    _rackhd_validator:
      name: rackhd_validator
      validateResponse: true
      schemaNameKey: x-swagger-schema

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: error_handler
      - cors
      - swagger_params_parser
      - swagger_locals
      - swagger_authn
      - swagger_authz
      - swagger_security
      - _swagger_validate
      - _rackhd_validator
      - express_compatibility
      - _router
      - _swagger_renderer

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
